### ISSUE TITLE
loading screen

### ISSUE THREAD

**Issue by EnzoCortinovis** [omarmelade/Tornado#1]
ecran de chargement qui apparait quand on revient en arriere depuis le menu principal de l'appli

**Comment by omarmelade** [comment]
# FIX : return to SplashScreen 👍 

In `onBackPressed()` method of `SplashActivity.java`, i'm now settin' the visibility to false.
That means that when the **back** button is pressed by the user on the Main screen, the SplashActivity desappears, and the app **close**.

Here's the code who do this : 
```    
....
@Override
public void onBackPressed() {
    super.onBackPressed();
    this.setVisible(false);
}
```
